[book]
authors = ["许杰友 Jieyou Xu (Joe)"]
language = "en"
multilingual = false
src = "src"
title = "Cogitator's Grimoire"

[rust]
edition = "2021"

[preprocessor.index]

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/jieyouxu/CogitatorsGrimoire"
input-404 = "not-found.md"
